# (1) 基本項目
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment

# (2) Deploymentのスペック
spec:
  replicas: 3   # レプリカ数
  selector:
    matchLabels:
      app: photo-view   # テンプレートの検索条件

  # (3) Podのテンプレート
  template:
    metadata:
      labels:
        app: photo-view
    spec:
      containers:
      - image: sampleacrregistry.azurecr.io/photo-view:v1.0   # コンテナイメージの場所
        name: photoview-container   # コンテナ名
        imagePullPolicy: Always   # コンテナイメージのpull条件

        # ポート番号
        ports:
        - containerPort: 80

        env:
        # Secretsを環境変数に設定
        - name: SECRET_ID
          valueFrom:
            secretKeyRef:
              name: api-key
              key: id
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-key
              key: key

        # Secretsのマウント設定
        volumeMounts:
          - name: secrets-volume
            mountPath: /etc/secrets
            readOnly: true

      # Secretsのボリュームのマウント
      volumes:
        - name: secrets-volume
          secret:
            secretName: apl-auth
