# (1) 基本項目
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-deployment

# (2) Deploymentのスペック
spec:
  replicas: 3   # レプリカ数
  selector:
    matchLabels:
      app: config-view   # テンプレートの検索条件

  # (3) Podのテンプレート
  template:
    metadata:
      labels:
        app: config-view
    spec:
      containers:
      - image: sampleacrregistry.azurecr.io/photo-view:v3.0   # コンテナイメージの場所
        name: photoview-container   # コンテナ名
        imagePullPolicy: Always   # コンテナイメージのpull条件

        # ポート番号
        ports:
        - containerPort: 80

        # ConfigMapを環境変数に設定
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: project-config
              key: project.id

        # ConfigMapのマウント設定
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config

      # ConfigMapのボリュームのマウント
      volumes:
        - name: config-volume
          configMap:
            name: app-config
---
# (1) 基本項目
apiVersion: v1
kind: Service
metadata:
  name: webserver

# (2) Serviceのスペック
spec:
  type: LoadBalancer
  ports:   # ポート番号
    - port: 80
      targetPort: 80
      protocol: TCP
  
  # (3) Podの条件(ラベル)
  selector:
    app: config-view

