apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8sbook-dev-rolebinding
  namespace: k8sbook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8sbook-dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "${K8SBOOK_DEVUSER}"