kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: k8sbook
  name: k8sbook-dev
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "pods/log"]
  verbs: ["*"]