apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sbook-pod-reader
  namespace: k8sbook
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sbook-pod-reader-rolebinding
  namespace: k8sbook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: k8sbook-pod-reader