apiVersion: v1
kind: Service
metadata:
  name: gke-flask-frontend
  labels:
    app: gke-flask
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: gke-flask
    tier: frontend
