# A. 基本項目
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment

# B. Deploymentのスペック
spec:
  replicas: 10   # レプリカ数

  # ローリングアップデートの設定
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 30%
      maxUnavailable: 10%

  selector:
    matchLabels:
      app: photo-view   # テンプレートの検索条件

  # C. Podのテンプレート
  template:
    metadata:
      labels:
        app: photo-view
    spec:
      containers:
      - image: asaacrregistry.azurecr.io/photo-view:v2.0   # コンテナイメージの場所
        name: photoview-container   # コンテナ名
        ports:
        - containerPort: 80   # ポート番号
