# A. 基本項目
apiVersion: v1
kind: Service
metadata:
  name: webserver

# B. Serviceのスペック
spec:
  type: LoadBalancer
  ports:   # ポート番号
    - port: 80
      targetPort: 80
      protocol: TCP
  
  # C. Podの条件(ラベル)
  selector:
    app: nginx