# (1) 基本項目
apiVersion: v1
kind: Pod
metadata:
  name: limits-pod

# (2) Podのスペック
spec:
  #restartPolicy: OnFailure 
  
  # (3) コンテナの仕様
  containers:
  - name: main
    image: polinux/stress
    resources:
      limits:
        cpu: 400m
        memory: 1Gi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "500M", "--vm-hang", "1"]
